package basisFx;

import basisFx.dataSource.DbSchema;

public class DbSchemaPrice extends DbSchema {

    public void create() {

        String img = "CREATE CACHED  TABLE IF NOT EXISTS IMG ( "
                + "	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  "
                + "	barcode VARCHAR(15),  "
                + "	imgSmall Blob,"
                + "	imgBig Blob,"
                + " UNIQUE  (barcode)"
                + ")";


        String storedCategory = "CREATE   TABLE IF NOT EXISTS StoredCategory ( "
                + "	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  "
                + "	rank INTEGER,  "
                + "	name  VARCHAR(200) "
                + ")";


        String priceItem = "CREATE   TABLE IF NOT EXISTS PriceItem ( "
                + "	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  "
                + "	storedCategoryId INTEGER,  "
                + "	imgId INTEGER,  "
                + "	name  VARCHAR(200),  "
                + "	alias  VARCHAR(200),  "
                + "	barcode  VARCHAR(15),  "
                + "	orderNumber  VARCHAR(15),  "
                + "	pure_order  VARCHAR(15),  "
                + "	visibitity Boolean,  "
                + " FOREIGN KEY (storedCategoryId) REFERENCES StoredCategory(id) on delete cascade , "
                + " FOREIGN KEY (imgId) REFERENCES IMG(id) on delete cascade , "
                + " UNIQUE  (barcode, pure_order)"
                + ")";



        String outputTamplate = "CREATE   TABLE IF NOT EXISTS OutputTemplate ( "
                + "	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  "
                + "	name  VARCHAR(200) Not null, "
                + "	storedCategory  INTEGER Array Not null"
                + ")";




        init(
                img,
                outputTamplate,
                storedCategory,
                priceItem
        );

    }
    }
